#!/bin/bash
# FILENAME:  expt2.sub
##SBATCH  -A highmem
#SBATCH  -A standby
#SBATCH  --nodes=16
#SBATCH  --time=2:00:00
#SBATCH  --ntasks-per-node=1
#SBATCH  --mem=30G
##SBATCH --exclusive

module load gcc
module load openmpi

cd $SLURM_SUBMIT_DIR

#file=/scratch/bell/gopals/webdocs/6/webdocs.mtx
#file=/scratch/bell/gopals/com-Friendster/31/com-Friendster.mtx
#file=/scratch/bell/gopals/com-Friendster/com-Friendster.mtx
#file=/scratch/bell/gopals/av41092_f.mtx
#file=../data/lhr01.mtx
#file=../data/SmallTest.mtx
#file=/scratch/bell/gopals/tiny-imagenet-vectors/train/tiny_image_train.mtx
#file=/scratch/bell/gopals/belgium_osm/belgium_osm.mtx
#file=/scratch/bell/gopals/road_usa/road_usa.mtx 
#mpirun  -n 128 ./mpi_hello
#mpirun  -n 2 ../build/apps/mpi_hello 

k=8000
m=16
b=2
#file=/scratch/bell/gopals/road_usa/32/road_usa.mtx
#file=/scratch/bell/gopals/webdocs/6/webdocs.mtx
file=/scratch/bell/gopals/com-Friendster/16/com-Friendster.mtx
srun --mpi=pmi2 -n $m /usr/bin/time -v ./apps/testgreeDiL2 $file  $k $b

m=8
b=4
#file=/scratch/bell/gopals/road_usa/16/road_usa.mtx
#file=/scratch/bell/gopals/webdocs/7/webdocs.mtx
file=/scratch/bell/gopals/com-Friendster/8/com-Friendster.mtx
srun --mpi=pmi2 -n $m /usr/bin/time -v ./apps/testgreeDiL2 $file  $k $b
m=4
b=4
#file=/scratch/bell/gopals/road_usa/8/road_usa.mtx
#file=/scratch/bell/gopals/webdocs/5/webdocs.mtx
file=/scratch/bell/gopals/com-Friendster/4/com-Friendster.mtx
srun --mpi=pmi2 -n $m /usr/bin/time -v ./apps/testgreeDiL2 $file  $k $b 

#srun --mpi=pmi2 -n 2 valgrind --tool=massif --time-unit=B ./apps/testgreeDiL2 $file 100 2
