#!/bin/bash
# FILENAME:  test_lg.sub
#SBATCH  --time=02:00:00
#SBATCH  -A standby
#SBATCH  --mem=200G

module load gcc
module load openmpi

cd $SLURM_SUBMIT_DIR

#file=/scratch/bell/gopals/tiny_image_train.mtx
#file=/scratch/bell/gopals/com-Friendster/com-Friendster.mtx
file=/scratch/bell/gopals/av41092_f.mtx
#file=../data/lhr01.mtx
#file=../data/SmallSymTest.mtx

#mpirun  -n 128 ./mpi_hello
#mpirun  -n 2 ../build/apps/mpi_hello 
srun  ./apps/rdmpart $file 32
