#!/bin/bash
# FILENAME:  expt1.sub
##SBATCH  -A highmem
#SBATCH  -A standby
#SBATCH  --nodes=256
#SBATCH  --time=3:50:00
#SBATCH  --ntasks-per-node=1
#SBATCH  --mem=10G
##SBATCH --exclusive

module load gcc
module load openmpi

cd $SLURM_SUBMIT_DIR

filep=/scratch/bell/gopals/com-Friendster/com-Friendster/
#filep=/scratch/bell/gopals/AGATHA_2015/

filen=com-Friendster.mtx
#filen=AGATHA_2015.mtx

#outputfile=../data/outFrnd.csv
outputfile=../data/outFrnd50.csv
#outputfile=../data/outFrnd10000.csv
#outputfile=../data/outAgaatha.csv


b=2

folders=(
024
032
040
048
056
064
072
080
088
096
104
112
120
128
136
144
152
160
168
176
184
192
200
208
216
224
232
240
248
256
)

#for value in {1..5}
for m in ${folders[@]};
do
	for value in {1..5}
	#for m in ${folders[@]};
	do
		k=100
		srun --mpi=pmi2 -n $m ./apps/testgreeDiL2 $filep$m/$filen $k $b $outputfile
		srun --mpi=pmi2 -n $m ./apps/testgreeDiL2 $filep$m/$filen $k $m $outputfile
		
		#k=160
		#srun --mpi=pmi2 -n $m ./apps/testgreeDiL2 $filep$m/$filen $k $b  $outputfile
		#srun --mpi=pmi2 -n $m ./apps/testgreeDiL2 $filep$m/$filen $k $m  $outputfile
	done
done

