#!/bin/bash
# FILENAME:  expt1.sub
##SBATCH  -A highmem
#SBATCH  -A standby
#SBATCH  --nodes=128
#SBATCH  --time=1:30:00
#SBATCH  --ntasks-per-node=1
#SBATCH  --mem=20G
##SBATCH --exclusive

module load gcc
module load openmpi

cd $SLURM_SUBMIT_DIR

#filep=/scratch/bell/gopals/com-Friendster/com-Friendster/
filep=/scratch/bell/gopals/AGATHA_2015/

#filen=com-Friendster.mtx
filen=AGATHA_2015.mtx

k=1000
b=2
m=004
m=008
/usr/bin/time -v srun --mpi=pmi2 -n $m ./apps/testgreeDiL2 $filep$m/$filen  $k $b
m=012
m=016
/usr/bin/time -v srun --mpi=pmi2 -n $m ./apps/testgreeDiL2 $filep$m/$filen  $k $b
m=020
m=024
/usr/bin/time -v srun --mpi=pmi2 -n $m ./apps/testgreeDiL2 $filep$m/$filen  $k $b
m=028
m=032
/usr/bin/time -v srun --mpi=pmi2 -n $m ./apps/testgreeDiL2 $filep$m/$filen  $k $b
m=036
m=040
/usr/bin/time -v srun --mpi=pmi2 -n $m ./apps/testgreeDiL2 $filep$m/$filen  $k $b
m=044
m=048
/usr/bin/time -v srun --mpi=pmi2 -n $m ./apps/testgreeDiL2 $filep$m/$filen  $k $b
m=052
m=056
/usr/bin/time -v srun --mpi=pmi2 -n $m ./apps/testgreeDiL2 $filep$m/$filen  $k $b
m=060
m=064
/usr/bin/time -v srun --mpi=pmi2 -n $m ./apps/testgreeDiL2 $filep$m/$filen  $k $b
m=068
m=072
/usr/bin/time -v srun --mpi=pmi2 -n $m ./apps/testgreeDiL2 $filep$m/$filen  $k $b
m=076
m=080
/usr/bin/time -v srun --mpi=pmi2 -n $m ./apps/testgreeDiL2 $filep$m/$filen  $k $b
m=084
m=088
/usr/bin/time -v srun --mpi=pmi2 -n $m ./apps/testgreeDiL2 $filep$m/$filen  $k $b
m=092
m=096
/usr/bin/time -v srun --mpi=pmi2 -n $m ./apps/testgreeDiL2 $filep$m/$filen  $k $b
m=100
m=104
/usr/bin/time -v srun --mpi=pmi2 -n $m ./apps/testgreeDiL2 $filep$m/$filen  $k $b
m=108
m=112
/usr/bin/time -v srun --mpi=pmi2 -n $m ./apps/testgreeDiL2 $filep$m/$filen  $k $b
m=116
m=120
/usr/bin/time -v srun --mpi=pmi2 -n $m ./apps/testgreeDiL2 $filep$m/$filen  $k $b
m=124
m=128
/usr/bin/time -v srun --mpi=pmi2 -n $m ./apps/testgreeDiL2 $filep$m/$filen  $k $b

k=2000

k=8000


k=16000
m=004
m=008
/usr/bin/time -v srun --mpi=pmi2 -n $m ./apps/testgreeDiL2 $filep$m/$filen  $k $b
m=012
m=016
/usr/bin/time -v srun --mpi=pmi2 -n $m ./apps/testgreeDiL2 $filep$m/$filen  $k $b
m=020
m=024
/usr/bin/time -v srun --mpi=pmi2 -n $m ./apps/testgreeDiL2 $filep$m/$filen  $k $b
m=028
m=032
/usr/bin/time -v srun --mpi=pmi2 -n $m ./apps/testgreeDiL2 $filep$m/$filen  $k $b
m=036
m=040
/usr/bin/time -v srun --mpi=pmi2 -n $m ./apps/testgreeDiL2 $filep$m/$filen  $k $b
m=044
m=048
/usr/bin/time -v srun --mpi=pmi2 -n $m ./apps/testgreeDiL2 $filep$m/$filen  $k $b
m=052
m=056
/usr/bin/time -v srun --mpi=pmi2 -n $m ./apps/testgreeDiL2 $filep$m/$filen  $k $b
m=060
m=064
/usr/bin/time -v srun --mpi=pmi2 -n $m ./apps/testgreeDiL2 $filep$m/$filen  $k $b
m=068
m=072
/usr/bin/time -v srun --mpi=pmi2 -n $m ./apps/testgreeDiL2 $filep$m/$filen  $k $b
m=076
m=080
/usr/bin/time -v srun --mpi=pmi2 -n $m ./apps/testgreeDiL2 $filep$m/$filen  $k $b
m=084
m=088
/usr/bin/time -v srun --mpi=pmi2 -n $m ./apps/testgreeDiL2 $filep$m/$filen  $k $b
m=092
m=096
/usr/bin/time -v srun --mpi=pmi2 -n $m ./apps/testgreeDiL2 $filep$m/$filen  $k $b
m=100
m=104
/usr/bin/time -v srun --mpi=pmi2 -n $m ./apps/testgreeDiL2 $filep$m/$filen  $k $b
m=108
m=112
/usr/bin/time -v srun --mpi=pmi2 -n $m ./apps/testgreeDiL2 $filep$m/$filen  $k $b
m=116
m=120
/usr/bin/time -v srun --mpi=pmi2 -n $m ./apps/testgreeDiL2 $filep$m/$filen  $k $b
m=124
m=128
/usr/bin/time -v srun --mpi=pmi2 -n $m ./apps/testgreeDiL2 $filep$m/$filen  $k $b


