#!/bin/bash
# FILENAME:  expt1.sub
##SBATCH  -A highmem
#SBATCH  -A standby
#SBATCH  --nodes=128
#SBATCH  --time=1:30:00
#SBATCH  --ntasks-per-node=1
#SBATCH  --mem=20G
##SBATCH --exclusive

module load gcc
module load openmpi

cd $SLURM_SUBMIT_DIR

filep=/scratch/bell/gopals/com-Friendster/com-Friendster/
#filep=/scratch/bell/gopals/AGATHA_2015/

filen=com-Friendster.mtx
#filen=AGATHA_2015.mtx

outputfile=../data/outFrnd.csv
#outputfile=../data/outAgaatha.csv


b=2

folders=(
008
016
024
032
040
048
056
064
072
080
088
096
104
112
120
128)

for m in ${folders[@]};
do
	for value in {1..5}
	do
		k=100
		srun --mpi=pmi2 -n $m ./apps/testgreeDiL2 $filep$m/$filen $k $b $outputfile
		srun --mpi=pmi2 -n $m ./apps/testgreeDiL2 $filep$m/$filen $k $m $outputfile
		
		k=160
		srun --mpi=pmi2 -n $m ./apps/testgreeDiL2 $filep$m/$filen $k $b  $outputfile
		srun --mpi=pmi2 -n $m ./apps/testgreeDiL2 $filep$m/$filen $k $m  $outputfile
	done
done

