#!/bin/bash
# FILENAME:  test_greeDi2.sub
#SBATCH  -A standby
#SBATCH  --nodes=1
#SBATCH  --time=00:50:00
#SBATCH  --ntasks-per-node=16
##SBATCH  --mem=0
##SBATCH --exclusive

module load gcc
module load openmpi

cd $SLURM_SUBMIT_DIR

#file=/scratch/bell/gopals/com-Friendster/com-Friendster.mtx
#file=/scratch/bell/gopals/av41092_f.mtx
file=../data/lhr01.mtx
#file=../data/SmallTest.mtx

#mpirun  -n 128 ./mpi_hello
#mpirun  -n 2 ../build/apps/mpi_hello 

srun --mpi=pmi2 -n 16 ./apps/testgreeDiL2 $file 10 2
