#!/bin/bash
# FILENAME:  test_greeDi2.sub
#SBATCH  -A highmem
##SBATCH  -A standby
#SBATCH  --nodes=1
#SBATCH  --time=10:50:00
#SBATCH  --ntasks-per-node=32
##SBATCH  --mem=300G
##SBATCH --exclusive

module load gcc
module load openmpi

cd $SLURM_SUBMIT_DIR

#file=/scratch/bell/gopals/com-Friendster/com-Friendster.mtx
#file=/scratch/bell/gopals/av41092_f.mtx
#file=../data/lhr01.mtx
#file=../data/SmallTest.mtx
file=/scratch/bell/gopals/tiny-imagenet-vectors/train/tiny_image_train.mtx
#mpirun  -n 128 ./mpi_hello
#mpirun  -n 2 ../build/apps/mpi_hello 

srun --mpi=pmi2 -n 32 /usr/bin/time -v ./apps/testgreeDiL2Medoid $file 500 16 

#srun --mpi=pmi2 -n 2 valgrind --tool=massif --time-unit=B ./apps/testgreeDiL2 $file 100 2
